apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  namespace: abdullah-tawazun
  labels:
    app: sql
    name: abdullahqobia
spec:
  type: ClusterIP
  ports:
    - name: sql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: sql